// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('LoginLogoutTestAutoma', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LoginLogoutTestAutoma', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect(1366, 728)
    await driver.findElement(By.id("normal_login_username")).click()
    await driver.findElement(By.id("normal_login_username")).sendKeys("admin@esi.dz")
    await driver.findElement(By.id("normal_login_password")).click()
    await driver.findElement(By.id("normal_login_password")).sendKeys("admin@esi.dz")
    await driver.findElement(By.css(".ant-btn")).click()
    await driver.findElement(By.linkText("Deconxion")).click()
  })
})
